# Generated by Django 6.0.3 on 2026-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='所属'),
        ),
        migrations.AddField(
            model_name='report',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='氏名'),
        ),
        migrations.AddField(
            model_name='report',
            name='goal',
            field=models.CharField(blank=True, max_length=255, verbose_name='目標'),
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, verbose_name='総括'),
        ),
        migrations.AddField(
            model_name='report',
            name='task1',
            field=models.CharField(blank=True, max_length=255, verbose_name='タスク1'),
        ),
        migrations.AddField(
            model_name='report',
            name='task2',
            field=models.CharField(blank=True, max_length=255, verbose_name='タスク2'),
        ),
        migrations.AddField(
            model_name='report',
            name='task3',
            field=models.CharField(blank=True, max_length=255, verbose_name='タスク3'),
        ),
        migrations.AddField(
            model_name='report',
            name='work_detail1',
            field=models.CharField(blank=True, max_length=255, verbose_name='業務詳細1'),
        ),
        migrations.AddField(
            model_name='report',
            name='work_detail2',
            field=models.CharField(blank=True, max_length=255, verbose_name='業務詳細2'),
        ),
        migrations.AddField(
            model_name='report',
            name='work_detail3',
            field=models.CharField(blank=True, max_length=255, verbose_name='業務詳細3'),
        ),
        migrations.AddField(
            model_name='report',
            name='work_detail4',
            field=models.CharField(blank=True, max_length=255, verbose_name='業務詳細4'),
        ),
        migrations.AddField(
            model_name='report',
            name='work_time1',
            field=models.CharField(blank=True, max_length=50, verbose_name='時間1'),
        ),
        migrations.AddField(
            model_name='report',
            name='work_time2',
            field=models.CharField(blank=True, max_length=50, verbose_name='時間2'),
        ),
        migrations.AddField(
            model_name='report',
            name='work_time3',
            field=models.CharField(blank=True, max_length=50, verbose_name='時間3'),
        ),
        migrations.AddField(
            model_name='report',
            name='work_time4',
            field=models.CharField(blank=True, max_length=50, verbose_name='時間4'),
        ),
        migrations.AlterField(
            model_name='report',
            name='work_date',
            field=models.DateField(verbose_name='作業日'),
        ),
    ]
