# Generated by Django 6.0.3 on 2026-04-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_content_remove_report_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
